// REGION ID REFERENCE:
// 1: North Hyrule Field     6: Great Hyrule Forest      11: Mount Lanayru
// 2: South Hyrule Field     7: Eldin                    12: East Necluda
// 3: Hyrule Ridge           8: Akkala                   13: Faron Grasslands
// 4: Hebra Mountains        9: Lanayru Great Spring     14: Gerudo Desert
// 5: Tabantha Tundra       10: Lanayru Wetlands         15: Gerudo Highlands

const landmarks = [
// TOWERS
    { name: "Lookout Landing", landmark: "Tower", type: "Skyview Tower", region: 1, level: "Surface", x: -298, y: 142, z: 25, details: "" },
	{ name: "Hyrule Field", landmark: "Tower", type: "Skyview Tower", region: 2, level: "Surface", x: -761, y: -1019, z: 64, details: "" },
	{ name: "Lindor's Brow", landmark: "Tower", type: "Skyview Tower", region: 3, level: "Surface", x: -1909, y: 1245, z: 297, details: "" },
	{ name: "Rospro Pass", landmark: "Tower", type: "Skyview Tower", region: 4, level: "Surface", x: -3860, y: 2345, z: 233, details: "" },
	{ name: "Pikida Stonegrove", landmark: "Tower", type: "Skyview Tower", region: 5, level: "Surface", x: -2312, y: 3064, z: 536, details: "" },
	{ name: "Typhlo Ruins", landmark: "Tower", type: "Skyview Tower", region: 6, level: "Surface", x: 343, y: 3133, z: 180, details: "" },
	{ name: "Eldin Canyon", landmark: "Tower", type: "Skyview Tower", region: 7, level: "Surface", x: 1641, y: 1190, z: 225, details: "" },
	{ name: "Ulri Mountain", landmark: "Tower", type: "Skyview Tower", region: 8, level: "Surface", x: 3497, y: 2025, z: 188, details: "" },
	{ name: "Upland Zorana", landmark: "Tower", type: "Skyview Tower", region: 9, level: "Surface", x: 2865, y: 580, z: 379, details: "" },
	{ name: "Sahasra Slope", landmark: "Tower", type: "Skyview Tower", region: 10, level: "Surface", x: 1341, y: -1176, z: 166, details: "" },
	{ name: "Mount Lanayru", landmark: "Tower", type: "Skyview Tower", region: 11, level: "Surface", x: 3847, y: -1313, z: 539, details: "" },
	{ name: "Rabella Wetlands", landmark: "Tower", type: "Skyview Tower", region: 12, level: "Surface", x: 2419, y: -2755, z: 222, details: "" },
	{ name: "Popla Foothills", landmark: "Tower", type: "Skyview Tower", region: 13, level: "Surface", x: 604, y: -2127, z: 98, details: "" },
	{ name: "Gerudo Canyon", landmark: "Tower", type: "Skyview Tower", region: 14, level: "Surface", x: -2438, y: -2182, z: 307, details: "" },
	{ name: "Gerudo Highlands", landmark: "Tower", type: "Skyview Tower", region: 15, level: "Surface", x: -3959, y: -1313, z: 422, details: "" },
// SHRINES
    { name: "Ishodag Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 1, level: "Surface", x: -885, y: 418, z: 49, details: "" },
	{ name: "Jiosin Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 1, level: "Surface", x: -240, y: -374, z: 27, details: "" },
	{ name: "Kyononis Shrine", landmark: "Shrine", type: "Combat Training", region: 1, level: "Surface", x: -205, y: 451, z: 21, details: "" },
	{ name: "Sepapa Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 1, level: "Surface", x: 219, y: 1082, z: 26, details: "" },
	{ name: "Serutabomac Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 1, level: "Surface", x: -180, y: 1170, z: 280, details: "" },
	{ name: "Susuyai Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 1, level: "Surface", x: -785, y: -433, z: 18, details: "" },
	{ name: "Yamiyo Shrine", landmark: "Shrine", type: "Combat Training", region: 1, level: "Surface", x: 333, y: 468, z: 29, details: "" },
	{ name: "In-isa Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Sky", x: 27, y: -1506, z: 1408, details: "" },
	{ name: "Jinodok Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 2, level: "Sky", x: -1257, y: -1487, z: 1008, details: "" },
	{ name: "Ukouh Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Sky", x: 275, y: -910, z: 1474, details: "" },
	{ name: "Kamizun Shrine", landmark: "Shrine", type: "Proving Grounds", region: 2, level: "Surface", x: -176, y: -1557, z: 23, details: "" },
	{ name: "Kyokugon Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -710, y: -1550, z: 6, details: "" },
	{ name: "Mayachin Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -705, y: -866, z: 31, details: "" },
	{ name: "Riogok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -1443, y: -1616, z: 89, details: "" },
	{ name: "Sonapan Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -1921, y: -356, z: 228, details: "" },
	{ name: "Tadarok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -1082, y: -2187, z: 128, details: "" },
	{ name: "Tajikats Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: 344, y: -1007, z: 16, details: "" },
	{ name: "Teniten Shrine", landmark: "Shrine", type: "Combat Training", region: 2, level: "Surface", x: -73, y: -1115, z: 21, details: "" },
	{ name: "Tsutsu-um Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 2, level: "Surface", x: -1422, y: -1350, z: 68, details: "" },
	{ name: "Usazum Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 2, level: "Surface", x: -2140, y: -873, z: 93, details: "" },
	{ name: "Ga-ahisas Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 3, level: "Sky", x: -3596, y: 962, z: 1699, details: "" },
	{ name: "Ganos Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 3, level: "Sky", x: -3366, y: 469, z: 1695, details: "" },
	{ name: "Taunhiy Shrine", landmark: "Shrine", type: "Combat Training", region: 3, level: "Sky", x: -2400, y: 824, z: 615, details: "" },
	{ name: "Ikatak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 3, level: "Surface", x: -3950, y: 1138, z: 111, details: "" },
	{ name: "Iun-orok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 3, level: "Surface", x: -3538, y: 853, z: -133, details: "" },
	{ name: "Kiuyoyou Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 3, level: "Surface", x: -1106, y: 2086, z: 104, details: "" },
	{ name: "Makurukis Shrine", landmark: "Shrine", type: "Combat Training", region: 3, level: "Surface", x: -2848, y: 629, z: 233, details: "" },
	{ name: "Oromuwak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 3, level: "Surface", x: -3079, y: 1618, z: -241, details: "" },
	{ name: "Runakit Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 3, level: "Surface", x: -2534, y: 1167, z: 177, details: "" },
	{ name: "Sinakawak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 3, level: "Surface", x: -1413, y: 757, z: 89, details: "" },
	{ name: "Taki-ihaban Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 3, level: "Surface", x: -1828, y: 1196, z: 147, details: "" },
	{ name: "Ijo-o Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Sky", x: -3863, y: 2684, z: 702, details: "" },
	{ name: "Kahatanaum Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 4, level: "Sky", x: -3294, y: 3430, z: 1347, details: "" },
	{ name: "Mayaumekis Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Sky", x: -2947, y: 3051, z: 897, details: "" },
	{ name: "Eutoum Shrine", landmark: "Shrine", type: "Proving Grounds", region: 4, level: "Surface", x: -3506, y: 3570, z: 387, details: "" },
	{ name: "Gatakis Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Surface", x: -3650, y: 1805, z: 168, details: "" },
	{ name: "Otak Shrine", landmark: "Shrine", type: "Proving Grounds", region: 4, level: "Surface", x: -4391, y: 3714, z: 212, details: "" },
	{ name: "Rutafu-um Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 4, level: "Surface", x: -2996, y: 3102, z: 529, details: "" },
	{ name: "Sahirow Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Surface", x: -3355, y: 2387, z: 361, details: "" },
	{ name: "Sisuran Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 4, level: "Surface", x: -2559, y: 3353, z: 245, details: "" },
	{ name: "Tauyosipun Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Surface", x: -4539, y: 2881, z: 262, details: "" },
	{ name: "Wao-os Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 4, level: "Surface", x: -4059, y: 1991, z: 183, details: "" },
	{ name: "Taninoud Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 5, level: "Sky", x: -1800, y: 3406, z: 949, details: "" },
	{ name: "Tenbez Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 5, level: "Sky", x: -970, y: 3536, z: 1011, details: "" },
	{ name: "Mayaotaki Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 5, level: "Surface", x: -823, y: 3535, z: 235, details: "" },
	{ name: "Mayausiy Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 5, level: "Surface", x: -1165, y: 2602, z: 86, details: "" },
	{ name: "Nouda Shrine", landmark: "Shrine", type: "Proving Grounds", region: 5, level: "Surface", x: -2319, y: 2201, z: 173, details: "" },
	{ name: "Orochium Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 5, level: "Surface", x: -1638, y: 2643, z: 238, details: "" },
	{ name: "Oshozan-u Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 5, level: "Surface", x: -1404, y: 3677, z: 288, details: "" },
	{ name: "Mayam Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Sky", x: 341, y: 2814, z: 1821, details: "" },
	{ name: "Simosiwak Shrine", landmark: "Shrine", type: "Proving Grounds", region: 6, level: "Sky", x: 163, y: 1973, z: 759, details: "" },
	{ name: "Kikakin Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 6, level: "Surface", x: -395, y: 2736, z: 287, details: "" },
	{ name: "Mayak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 6, level: "Surface", x: 1270, y: 3733, z: 106, details: "" },
	{ name: "Minetak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Surface", x: 393, y: 3485, z: 68, details: "" },
	{ name: "Musanokir Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 6, level: "Surface", x: 408, y: 2133, z: 143, details: "" },
	{ name: "Ninjis Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Surface", x: 353, y: 1890, z: 178, details: "" },
	{ name: "Pupunke Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Surface", x: 619, y: 2211, z: 164, details: "" },
	{ name: "Sakunbomar Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Surface", x: 166, y: 2319, z: 178, details: "" },
	{ name: "Sikukuu Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 6, level: "Surface", x: 700, y: 2793, z: 225, details: "" },
	{ name: "Tenmaten Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 6, level: "Surface", x: -594, y: 1551, z: -14, details: "" },
	{ name: "Kadaunar Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Sky", x: 1883, y: 1202, z: 1251, details: "" },
	{ name: "Ekochiu Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 1059, y: 1276, z: 45, details: "" },
	{ name: "Isisim Shrine", landmark: "Shrine", type: "Proving Grounds", region: 7, level: "Surface", x: 1842, y: 2841, z: 363, details: "" },
	{ name: "Jiotak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 7, level: "Surface", x: 1833, y: 3179, z: 257, details: "" },
	{ name: "Kimayat Shrine", landmark: "Shrine", type: "Proving Grounds", region: 7, level: "Surface", x: 2863, y: 3637, z: 239, details: "" },
	{ name: "Kisinona Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 2567, y: 1245, z: 173, details: "" },
	{ name: "Marakuguc Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 1761, y: 2508, z: 437, details: "" },
	{ name: "Momosik Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 7, level: "Surface", x: 2959, y: 2758, z: 524, details: "" },
	{ name: "Moshapin Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 7, level: "Surface", x: 2678, y: 1905, z: 131, details: "" },
	{ name: "Sibajitak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 2401, y: 3273, z: 402, details: "" },
	{ name: "Sitsum Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 2367, y: 2598, z: 790, details: "" },
	{ name: "Timawak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 7, level: "Surface", x: 1798, y: 1639, z: 311, details: "" },
	{ name: "Gikaku Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 8, level: "Sky", x: 4506, y: 2164, z: 1155, details: "" },
	{ name: "Mogisari Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Sky", x: 4655, y: 3501, z: 1010, details: "" },
	{ name: "Natak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 8, level: "Sky", x: 3669, y: 1488, z: 1157, details: "" },
	{ name: "Domizuin Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Surface", x: 3305, y: 1443, z: 426, details: "" },
	{ name: "Gemimik Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Surface", x: 4513, y: 2116, z: 1, details: "" },
	{ name: "Igashuk Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 8, level: "Surface", x: 4653, y: 3702, z: 131, details: "" },
	{ name: "Jochi-ihiga Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 8, level: "Surface", x: 3809, y: 1219, z: 90, details: "" },
	{ name: "Jochi-iu Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Surface", x: 4346, y: 2875, z: 164, details: "" },
	{ name: "Kamatukis Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Surface", x: 3431, y: 3355, z: 70, details: "" },
	{ name: "Mayachideg Shrine", landmark: "Shrine", type: "Proving Grounds", region: 8, level: "Surface", x: 3061, y: 1823, z: 216, details: "" },
	{ name: "Rasiwak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 8, level: "Surface", x: 4664, y: 3262, z: 2, details: "" },
	{ name: "Sinatanika Shrine", landmark: "Shrine", type: "Combat Training", region: 8, level: "Surface", x: 3839, y: 2301, z: 48, details: "" },
	{ name: "Igoshon Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Sky", x: 3480, y: 664, z: 1325, details: "" },
	{ name: "Jirutagumac Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Sky", x: 2916, y: 533, z: 951, details: "" },
	{ name: "Apogek Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Surface", x: 3887, y: -217, z: 163, details: "" },
	{ name: "Gatanisis Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Surface", x: 4498, y: 825, z: 95, details: "" },
	{ name: "Ihen-a Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Surface", x: 3784, y: 579, z: 486, details: "" },
	{ name: "Joniu Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 9, level: "Surface", x: 2918, y: 505, z: 155, details: "" },
	{ name: "Maoikes Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 9, level: "Surface", x: 2277, y: 150, z: 79, details: "" },
	{ name: "Mogawak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 9, level: "Surface", x: 3298, y: 424, z: 112, details: "" },
	{ name: "Rasitakiwak Shrine", landmark: "Shrine", type: "Proving Grounds", region: 9, level: "Surface", x: 4166, y: 1323, z: 229, details: "" },
	{ name: "Yomizuk Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 9, level: "Surface", x: 4412, y: -610, z: 34, details: "" },
	{ name: "Josiu Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 10, level: "Sky", x: 1759, y: -1208, z: 924, details: "" },
	{ name: "Ukoojisi Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 10, level: "Sky", x: 1470, y: -2170, z: 585, details: "" },
	{ name: "Yansamin Shrine", landmark: "Shrine", type: "Proving Grounds", region: 10, level: "Sky", x: 2349, y: -1782, z: 1475, details: "" },
	{ name: "Eshos Shrine", landmark: "Shrine", type: "Combat Training", region: 10, level: "Surface", x: 1564, y: -1945, z: 157, details: "" },
	{ name: "Jojon Shrine", landmark: "Shrine", type: "Proving Grounds", region: 10, level: "Surface", x: 1202, y: 329, z: 29, details: "" },
	{ name: "Jonsau Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 10, level: "Surface", x: 1743, y: 18, z: 25, details: "" },
	{ name: "Kurakat Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 10, level: "Surface", x: 2362, y: -511, z: 155, details: "" },
	{ name: "Makasura Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 10, level: "Surface", x: 1770, y: -1050, z: 166, details: "" },
	{ name: "Morok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 10, level: "Surface", x: 1183, y: -780, z: 133, details: "" },
	{ name: "O-ogim Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 10, level: "Surface", x: 2755, y: -1089, z: 100, details: "" },
	{ name: "Ren-iz Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 10, level: "Surface", x: 756, y: 823, z: 81, details: "" },
	{ name: "Tukarok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 10, level: "Surface", x: 915, y: -250, z: 34, details: "" },
	{ name: "Mayanas Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 11, level: "Sky", x: 4613, y: -947, z: 1790, details: "" },
	{ name: "Sihajog Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 11, level: "Sky", x: 4545, y: -845, z: 1121, details: "" },
	{ name: "Anedamimik Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 11, level: "Surface", x: 4231, y: -2178, z: -7, details: "" },
	{ name: "Jikais Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 11, level: "Surface", x: 4266, y: -1674, z: 181, details: "" },
	{ name: "Jogou Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 11, level: "Surface", x: 3346, y: -1188, z: 57, details: "" },
	{ name: "Mayahisik Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 11, level: "Surface", x: 3730, y: -2057, z: 189, details: "" },
	{ name: "Zakusu Shrine", landmark: "Shrine", type: "Proving Grounds", region: 11, level: "Surface", x: 3527, y: -1481, z: 167, details: "" },
	{ name: "Zanmik Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 11, level: "Surface", x: 3469, y: -2180, z: 148, details: "" },
	{ name: "Kumamayn Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 12, level: "Sky", x: 2856, y: -2857, z: 1212, details: "" },
	{ name: "Bamitok Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 12, level: "Surface", x: 3094, y: -3209, z: 81, details: "" },
	{ name: "Marari-In Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 12, level: "Surface", x: 4632, y: -3712, z: 18, details: "" },
	{ name: "Sifumim Shrine", landmark: "Shrine", type: "Proving Grounds", region: 12, level: "Surface", x: 2826, y: -3271, z: 78, details: "" },
	{ name: "Tokiy Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 12, level: "Surface", x: 2304, y: -2377, z: -28, details: "" },
	{ name: "Gutanbac Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Sky", x: 709, y: -1381, z: 1584, details: "" },
	{ name: "Joku-u Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Sky", x: 1376, y: -3340, z: 443, details: "" },
	{ name: "Joku-usin Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Sky", x: 1070, y: -3347, z: 785, details: "" },
	{ name: "Nachoyah Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Sky", x: 390, y: -1660, z: 2299, details: "" },
	{ name: "En-oma Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Surface", x: 104, y: -2517, z: 88, details: "" },
	{ name: "Ishokin Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Surface", x: -562, y: -3524, z: 129, details: "" },
	{ name: "Jiukoum Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Surface", x: 867, y: -2280, z: 141, details: "" },
	{ name: "Jochisiu Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Surface", x: 931, y: -1902, z: 29, details: "" },
	{ name: "Joju-u-u Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Surface", x: 1516, y: -3576, z: 142, details: "" },
	{ name: "Susub Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Surface", x: 348, y: -2050, z: -26, details: "" },
	{ name: "Utojis Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 13, level: "Surface", x: 1217, y: -2542, z: 96, details: "" },
	{ name: "Utsushok Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 13, level: "Surface", x: 669, y: -3358, z: 72, details: "" },
	{ name: "Rakashog Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Sky", x: -1715, y: -2119, z: 1149, details: "" },
	{ name: "Siyamotsus Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 14, level: "Sky", x: -1793, y: -3331, z: 1011, details: "" },
	{ name: "Chichim Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 14, level: "Surface", x: -3211, y: -3007, z: -49, details: "" },
	{ name: "Irasak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 14, level: "Surface", x: -4159, y: -3824, z: 28, details: "" },
	{ name: "Karahatag Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -3726, y: -3625, z: 43, details: "" },
	{ name: "Kitawak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -1529, y: -2928, z: 321, details: "" },
	{ name: "Kudanisar Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -4168, y: -2144, z: 50, details: "" },
	{ name: "Mayatat Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -3292, y: -2509, z: 23, details: "" },
	{ name: "Miryotanog Shrine", landmark: "Shrine", type: "Proving Grounds", region: 14, level: "Surface", x: -4679, y: -3086, z: 56, details: "" },
	{ name: "Motsusis Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 14, level: "Surface", x: -1795, y: -3485, z: 45, details: "" },
	{ name: "Rakakudaj Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 14, level: "Surface", x: -2031, y: -1847, z: 64, details: "" },
	{ name: "Siwakama Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -2445, y: -3345, z: 41, details: "" },
	{ name: "Soryotanog Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -3883, y: -2964, z: 125, details: "" },
	{ name: "Turakamik Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 14, level: "Surface", x: -2658, y: -2236, z: 67, details: "" },
	{ name: "Mayasiar Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 15, level: "Sky", x: -3544, y: -320, z: 1964, details: "" },
	{ name: "Gasas Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 15, level: "Surface", x: -4152, y: 98, z: 40, details: "" },
	{ name: "Mayamats Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 15, level: "Surface", x: -4637, y: -1514, z: 452, details: "" },
	{ name: "Otutsum Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 15, level: "Surface", x: -4468, y: -670, z: 509, details: "" },
	{ name: "Rotsumamu Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 15, level: "Surface", x: -3407, y: -1362, z: 35, details: "" },
	{ name: "Suariwak Shrine", landmark: "Shrine", type: "Rauru's Blessing", region: 15, level: "Surface", x: -2523, y: -1770, z: 132, details: "" },
	{ name: "Turakawak Shrine", landmark: "Shrine", type: "Puzzle Trial", region: 15, level: "Surface", x: -3496, y: -197, z: 66, details: "" },
// LIGHTROOTS
	{ name: "Apapes Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: 219, y: 1082, z: -474, details: "" },
	{ name: "Camobatures Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: -180, y: 1170, z: -515, details: "" },
	{ name: "Gadohsi Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: -885, y: 418, z: -497, details: "" },
	{ name: "Iayusus Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: -785, y: -433, z: -469, details: "" },
	{ name: "Nisoij Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: -240, y: -374, z: -478, details: "" },
	{ name: "Oyimay Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: 333, y: 468, z: -479, details: "" },
	{ name: "Sinonoyk Lightroot", landmark: "Lightroot", type: "", region: 1, level: "Depths", x: -205, y: 451, z: -472, details: "" },
	{ name: "Kogoir Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -1443, y: -1616, z: -538, details: "" },
	{ name: "Koradat Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -1082, y: -2187, z: -562, details: "" },
	{ name: "Mu-ustust Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -1422, y: -1350, z: -517, details: "" },
	{ name: "Muzasu Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -2140, y: -873, z: -542, details: "" },
	{ name: "Napanos Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -1921, y: -356, z: -635, details: "" },
	{ name: "Netinet Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -73, y: -1115, z: -471, details: "" },
	{ name: "Nihcayam Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -705, y: -866, z: -481, details: "" },
	{ name: "Nogukoyk Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -710, y: -1550, z: -517, details: "" },
	{ name: "Nuzimak Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: -176, y: -1557, z: -473, details: "" },
	{ name: "Stakijat Lightroot", landmark: "Lightroot", type: "", region: 2, level: "Depths", x: 344, y: -1007, z: -468, details: "" },
	{ name: "Kataki Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -3950, y: 1138, z: -551, details: "" },
	{ name: "Kawakanis Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -1413, y: 757, z: -538, details: "" },
	{ name: "Kawumoro Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -3079, y: 1618, z: -687, details: "" },
	{ name: "Koro-nui Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -3538, y: 853, z: -576, details: "" },
	{ name: "Nabahi-Ikat Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -1828, y: 1196, z: -723, details: "" },
	{ name: "Sikurukam Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -2848, y: 629, z: -621, details: "" },
	{ name: "Tikanur Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -2534, y: 1167, z: -623, details: "" },
	{ name: "Uoyoyuik Lightroot", landmark: "Lightroot", type: "", region: 3, level: "Depths", x: -1106, y: 2086, z: -554, details: "" },
	{ name: "Kato Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -4391, y: 3714, z: -702, details: "" },
	{ name: "Mu-ufatur Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -2996, y: 3102, z: -1027, details: "" },
	{ name: "Muotue Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -3506, y: 3570, z: -826, details: "" },
	{ name: "Narusis Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -2559, y: 3353, z: -690, details: "" },
	{ name: "Nupisoyuat Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -4539, y: 2881, z: -707, details: "" },
	{ name: "Sikatag Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -3650, y: 1805, z: -417, details: "" },
	{ name: "So-oaw Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -4059, y: 1991, z: -674, details: "" },
	{ name: "Worihas Lightroot", landmark: "Lightroot", type: "", region: 4, level: "Depths", x: -3355, y: 2387, z: -802, details: "" },
	{ name: "Aduon Lightroot", landmark: "Lightroot", type: "", region: 5, level: "Depths", x: -2319, y: 2201, z: -781, details: "" },
	{ name: "Ikatoayam Lightroot", landmark: "Lightroot", type: "", region: 5, level: "Depths", x: -823, y: 3535, z: -636, details: "" },
	{ name: "Muihcoro Lightroot", landmark: "Lightroot", type: "", region: 5, level: "Depths", x: -1638, y: 2643, z: -685, details: "" },
	{ name: "U-nazohso Lightroot", landmark: "Lightroot", type: "", region: 5, level: "Depths", x: -1404, y: 3677, z: -712, details: "" },
	{ name: "Yisuayam Lightroot", landmark: "Lightroot", type: "", region: 5, level: "Depths", x: -1165, y: 2602, z: -350, details: "" },
	{ name: "Eknupup Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 619, y: 2211, z: -611, details: "" },
	{ name: "Katenim Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 393, y: 3485, z: -594, details: "" },
	{ name: "Kayam Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 1270, y: 3733, z: -553, details: "" },
	{ name: "Netamnet Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: -594, y: 1551, z: -599, details: "" },
	{ name: "Nikakik Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: -395, y: 2736, z: -725, details: "" },
	{ name: "Ramobnukas Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 166, y: 2319, z: -625, details: "" },
	{ name: "Rikonasum Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 408, y: 2133, z: -592, details: "" },
	{ name: "Sijnin Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 353, y: 1890, z: -625, details: "" },
	{ name: "Uukukis Lightroot", landmark: "Lightroot", type: "", region: 6, level: "Depths", x: 700, y: 2793, z: -671, details: "" },
	{ name: "Anonisik Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2567, y: 1245, z: -600, details: "" },
	{ name: "Cugukaram Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 1761, y: 2508, z: -719, details: "" },
	{ name: "Katijabis Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2401, y: 3273, z: -844, details: "" },
	{ name: "Katoij Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 1833, y: 3179, z: -838, details: "" },
	{ name: "Kawamit Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 1798, y: 1639, z: -749, details: "" },
	{ name: "Kisomom Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2959, y: 2758, z: -963, details: "" },
	{ name: "Misisi Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 1842, y: 2841, z: -838, details: "" },
	{ name: "Mustis Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2367, y: 2598, z: -948, details: "" },
	{ name: "Nipahsom Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2678, y: 1905, z: -688, details: "" },
	{ name: "Tayamik Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 2863, y: 3637, z: -685, details: "" },
	{ name: "Uihcoke Lightroot", landmark: "Lightroot", type: "", region: 7, level: "Depths", x: 1059, y: 1276, z: -495, details: "" },
	{ name: "Agihi-Ihcoj Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 3809, y: 1219, z: -536, details: "" },
	{ name: "Akinatanis Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 3839, y: 2301, z: -488, details: "" },
	{ name: "Gedihcayam Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 3061, y: 1823, z: -662, details: "" },
	{ name: "Kawisar Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 4664, y: 3262, z: -454, details: "" },
	{ name: "Kimimeg Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 4513, y: 2116, z: -453, details: "" },
	{ name: "Kuhsagi Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 4653, y: 3702, z: -400, details: "" },
	{ name: "Niuzimod Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 3305, y: 1443, z: -790, details: "" },
	{ name: "Sikutamak Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 3431, y: 3355, z: -431, details: "" },
	{ name: "Ui-Ihcoj Lightroot", landmark: "Lightroot", type: "", region: 8, level: "Depths", x: 4346, y: 2875, z: -608, details: "" },
	{ name: "A-nehi Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 3784, y: 579, z: -926, details: "" },
	{ name: "Kawagom Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 3298, y: 424, z: -749, details: "" },
	{ name: "Kawikatisar Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 4166, y: 1323, z: -673, details: "" },
	{ name: "Kegopa Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 3887, y: -217, z: -608, details: "" },
	{ name: "Kuzimoy Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 4412, y: -610, z: -513, details: "" },
	{ name: "Sekioam Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 2277, y: 150, z: -501, details: "" },
	{ name: "Sisinatag Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 4498, y: 825, z: -535, details: "" },
	{ name: "Uinoj Lightroot", landmark: "Lightroot", type: "", region: 9, level: "Depths", x: 2918, y: 505, z: -795, details: "" },
	{ name: "Arusakam Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 1770, y: -1050, z: -61, details: "" },
	{ name: "Korakut Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 915, y: -250, z: -481, details: "" },
	{ name: "Korom Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 1183, y: -780, z: -500, details: "" },
	{ name: "Migo-o Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 2755, y: -1089, z: -54, details: "" },
	{ name: "Nojoj Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 1202, y: 329, z: -574, details: "" },
	{ name: "Sohse Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 1564, y: -1945, z: -464, details: "" },
	{ name: "Takaruk Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 2362, y: -511, z: -589, details: "" },
	{ name: "Uasnoj Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 1743, y: 18, z: -459, details: "" },
	{ name: "Zi-Ner Lightroot", landmark: "Lightroot", type: "", region: 10, level: "Depths", x: 756, y: 823, z: -531, details: "" },
	{ name: "Kimimadena Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 4231, y: -2178, z: -521, details: "" },
	{ name: "Kimnaz Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 3469, y: -2180, z: -594, details: "" },
	{ name: "Kisihayam Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 3730, y: -2057, z: -665, details: "" },
	{ name: "Siakij Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 4266, y: -1674, z: -628, details: "" },
	{ name: "Uogoj Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 3346, y: -1188, z: -610, details: "" },
	{ name: "Usukaz Lightroot", landmark: "Lightroot", type: "", region: 11, level: "Depths", x: 3527, y: -1481, z: -612, details: "" },
	{ name: "Kotimab Lightroot", landmark: "Lightroot", type: "", region: 12, level: "Depths", x: 3094, y: -3209, z: -594, details: "" },
	{ name: "Mimufis Lightroot", landmark: "Lightroot", type: "", region: 12, level: "Depths", x: 2826, y: -3271, z: -527, details: "" },
	{ name: "Ni-iraram Lightroot", landmark: "Lightroot", type: "", region: 12, level: "Depths", x: 4632, y: -3712, z: -506, details: "" },
	{ name: "Yikot Lightroot", landmark: "Lightroot", type: "", region: 12, level: "Depths", x: 2304, y: -2377, z: -617, details: "" },
	{ name: "Amo-Ne Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 104, y: -2517, z: -414, details: "" },
	{ name: "Busus Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 348, y: -2050, z: -471, details: "" },
	{ name: "Kohsustu Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 669, y: -3358, z: -484, details: "" },
	{ name: "Muokuij Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 867, y: -2280, z: -556, details: "" },
	{ name: "Nikohsi Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: -562, y: -3524, z: -574, details: "" },
	{ name: "Sijotu Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 1217, y: -2542, z: -612, details: "" },
	{ name: "U-u-ujoj Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 1516, y: -3576, z: -529, details: "" },
	{ name: "Uisihcoj Lightroot", landmark: "Lightroot", type: "", region: 13, level: "Depths", x: 931, y: -1902, z: -461, details: "" },
	{ name: "Amakawis Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -2445, y: -3345, z: -465, details: "" },
	{ name: "Gataharak Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -3726, y: -3625, z: -494, details: "" },
	{ name: "Gonatoyrim Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -4679, y: -3086, z: -503, details: "" },
	{ name: "Gonatoyros Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -3883, y: -2964, z: -434, details: "" },
	{ name: "Jadukakar Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -2031, y: -1847, z: -504, details: "" },
	{ name: "Kasari Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -4159, y: -3824, z: -478, details: "" },
	{ name: "Kawatik Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -1529, y: -2928, z: -731, details: "" },
	{ name: "Kimakarut Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -2658, y: -2236, z: -488, details: "" },
	{ name: "Mihcihc Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -3211, y: -3007, z: -470, details: "" },
	{ name: "Rasinaduk Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -4168, y: -2144, z: -487, details: "" },
	{ name: "Sisustom Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -1795, y: -3485, z: -477, details: "" },
	{ name: "Tatayam Lightroot", landmark: "Lightroot", type: "", region: 14, level: "Depths", x: -3292, y: -2509, z: -475, details: "" },
	{ name: "Kawakarut Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -3496, y: -197, z: -516, details: "" },
	{ name: "Kawiraus Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -2523, y: -1770, z: -713, details: "" },
	{ name: "Mustuto Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -4468, y: -670, z: -949, details: "" },
	{ name: "Sasag Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -4152, y: 98, z: -489, details: "" },
	{ name: "Stamayam Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -4637, y: -1514, z: -890, details: "" },
	{ name: "Umamustor Lightroot", landmark: "Lightroot", type: "", region: 15, level: "Depths", x: -3407, y: -1362, z: -77, details: "" },
// CAVES
	{ name: "Akkala Citadel Ruins Cave", landmark: "Cave", type: "", region: 8, level: "Surface", x: 3243, y: 1456, z: 294, details: "" },
	{ name: "Akkala Citadel Ruins Summit Cave", landmark: "Cave", type: "", region: 8, level: "Surface", x: 3292, y: 1492, z: 394, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 1 of 12)", region: 14, level: "Surface", x: -2584, y: -3638, z: -47, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 2 of 12)", region: 14, level: "Surface", x: -2535, y: -3626, z: -48, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 3 of 12)", region: 14, level: "Surface", x: -2480, y: -3632, z: -46, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 4 of 12)", region: 14, level: "Surface", x: -2604, y: -3709, z: -49, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 5 of 12)", region: 14, level: "Surface", x: -2564, y: -3681, z: -48, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 6 of 12)", region: 14, level: "Surface", x: -2518, y: -3671, z: -47, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 7 of 12)", region: 14, level: "Surface", x: -2451, y: -3676, z: -46, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 8 of 12)", region: 14, level: "Surface", x: -2570, y: -3744, z: -51, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 9 of 12)", region: 14, level: "Surface", x: -2521, y: -3724, z: -47, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 10 of 12)", region: 14, level: "Surface", x: -2477, y: -3709, z: -47, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 11 of 12)", region: 14, level: "Surface", x: -2530, y: -3769, z: -46, details: "" },
	{ name: "Ancient Altar Ruins", landmark: "Cave", type: "(Entrance 12 of 12)", region: 14, level: "Surface", x: -2480, y: -3758, z: -46, details: "" },
	{ name: "Ancient Columns Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -3465, y: 449, z: 254, details: "" },
	{ name: "Ancient Prison Ruins", landmark: "Cave", type: "", region: 14, level: "Surface", x: -3099, y: -3063, z: -51, details: "" },
	{ name: "Ancient Tree Stump Cave", landmark: "Cave", type: "", region: 1, level: "Surface", x: -1111, y: -432, z: 22, details: "" },
	{ name: "Ancient Zora Waterworks", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3606, y: 122, z: -1, details: "" },
	{ name: "Atun Valley Cave", landmark: "Cave", type: "", region: 12, level: "Surface", x: 2454, y: -3193, z: 64, details: "" },
	{ name: "Bone Pond East Cave", landmark: "Cave", type: "(Entrance 1 of 4)", region: 9, level: "Surface", x: 2185, y: 142, z: 37, details: "" },
	{ name: "Bone Pond East Cave", landmark: "Cave", type: "(Entrance 2 of 4)", region: 9, level: "Surface", x: 2215, y: 100, z: 71, details: "" },
	{ name: "Bone Pond East Cave", landmark: "Cave", type: "(Entrance 3 of 4)", region: 9, level: "Surface", x: 2260, y: 108, z: 110, details: "" },
	{ name: "Bone Pond East Cave", landmark: "Cave", type: "(Entrance 4 of 4)", region: 9, level: "Surface", x: 2253, y: 14, z: 16, details: "" },
	{ name: "Bottomless Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Sky", x: 739, y: -1358, z: 1542, details: "" },
	{ name: "Bottomless Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Sky", x: 711, y: -1449, z: 1485, details: "" },
	{ name: "Brightcap Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -3005, y: 1635, z: 199, details: "" },
	{ name: "Byroad to Lanayru Wetlands Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 10, level: "Surface", x: 1617, y: -1260, z: 6, details: "" },
	{ name: "Byroad to Lanayru Wetlands Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 10, level: "Surface", x: 1587, y: -812, z: 6, details: "" },
	{ name: "Calora Lake Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Surface", x: 1958, y: -3032, z: 192, details: "" },
	{ name: "Calora Lake Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Surface", x: 2009, y: -3164, z: 176, details: "" },
	{ name: "Cape Cales Cliffbase Cave", landmark: "Cave", type: "", region: 12, level: "Surface", x: 3650, y: -3210, z: -6, details: "" },
	{ name: "Cave Under Zora's Domain", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3240, y: 373, z: 75, details: "" },
	{ name: "Central Gerudo Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -3679, y: -3255, z: -18, details: "" },
	{ name: "Cephla Lake Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2593, y: 1330, z: 150, details: "" },
	{ name: "Coliseum Ruins Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -1167, y: -1310, z: 22, details: "" },
	{ name: "Construction Site Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 8, level: "Surface", x: 3678, y: 1538, z: 74, details: "" },
	{ name: "Construction Site Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 8, level: "Surface", x: 3735, y: 1534, z: 80, details: "" },
	{ name: "Cora Lakefront Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Surface", x: -171, y: -3067, z: -13, details: "" },
	{ name: "Cora Lakefront Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Surface", x: -256, y: -2940, z: -18, details: "" },
	{ name: "Corta Lake Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 1676, y: -3038, z: 164, details: "" },
	{ name: "Crenel Hills Cave", landmark: "Cave", type: "", region: 1, level: "Surface", x: 493, y: 730, z: 40, details: "" },
	{ name: "Crenel Peak Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 1, level: "Surface", x: 1144, y: 247, z: 57, details: "" },
	{ name: "Crenel Peak Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 1, level: "Surface", x: 1349, y: 296, z: 28, details: "" },
	{ name: "Cucco Hideaway", landmark: "Cave", type: "", region: 10, level: "Surface", x: 1877, y: -1160, z: 198, details: "" },
	{ name: "Death Mountain East Tunnel", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2767, y: 2778, z: 521, details: "" },
	{ name: "Death Mountain Foothill Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1949, y: 2687, z: 425, details: "" },
	{ name: "Death Mountain West Tunnel", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2238, y: 2682, z: 520, details: "" },
	{ name: "Deepback Bay Cave", landmark: "Cave", type: "", region: 11, level: "Surface", x: 4213, y: -2262, z: 0, details: "" },
	{ name: "Deplian Badlands Cave", landmark: "Cave", type: "", region: 6, level: "Surface", x: 307, y: 3579, z: 87, details: "" },
	{ name: "Dueling Peaks North Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 1194, y: -1854, z: 157, details: "" },
	{ name: "Dueling Peaks South Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 1183, y: -1947, z: 245, details: "" },
	{ name: "East Biron Snowshelf Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 4, level: "Surface", x: -3989, y: 3062, z: 138, details: "" },
	{ name: "East Biron Snowshelf Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 4, level: "Surface", x: -3555, y: 3088, z: 273, details: "" },
	{ name: "East Gerudo Ruins Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -2696, y: -2808, z: -67, details: "" },
	{ name: "East Restaurant Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1853, y: 1719, z: 291, details: "" },
	{ name: "Eventide Island Cave", landmark: "Cave", type: "", region: 12, level: "Surface", x: 4752, y: -3781, z: -6, details: "" },
	{ name: "Finra Woods Excavation Site", landmark: "Cave", type: "", region: 13, level: "Surface", x: 568, y: -2981, z: 12, details: "" },
	{ name: "Floria River Upstream Excavation", landmark: "Cave", type: "", region: 13, level: "Surface", x: 809, y: -2971, z: 10, details: "" },
	{ name: "Foothill Monster Den", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2275, y: 1520, z: 157, details: "" },
	{ name: "Fort Hateno Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 2243, y: -1689, z: 23, details: "" },
	{ name: "Gerudo Canyon Mine", landmark: "Cave", type: "(Entrance 1 of 2)", region: 14, level: "Surface", x: -2676, y: -2402, z: 79, details: "" },
	{ name: "Gerudo Canyon Mine", landmark: "Cave", type: "(Entrance 2 of 2)", region: 14, level: "Surface", x: -2611, y: -2604, z: 112, details: "" },
	{ name: "Gerudo Great Skeleton Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -4814, y: -3875, z: -1, details: "" },
	{ name: "Gerudo Sanctuary", landmark: "Cave", type: "(Entrance 1 of 2)", region: 14, level: "Surface", x: -3763, y: -2420, z: 24, details: "" },
	{ name: "Gerudo Sanctuary", landmark: "Cave", type: "(Entrance 2 of 2)", region: 14, level: "Surface", x: -3763, y: -2698, z: 35, details: "" },
	{ name: "Gisa Crater Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 3, level: "Surface", x: -3865, y: 1011, z: 72, details: "" },
	{ name: "Gisa Crater Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 3, level: "Surface", x: -3931, y: 1090, z: 72, details: "" },
	{ name: "Gorko Tunnel", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2015, y: 2038, z: 420, details: "" },
	{ name: "Goronbi River Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1423, y: 2102, z: 284, details: "" },
	{ name: "Great Plateau Foothill Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -832, y: -1488, z: 26, details: "" },
	{ name: "Hebra Great Skeleton Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3814, y: 3595, z: 255, details: "" },
	{ name: "Hebra Headspring Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -2900, y: 2510, z: 387, details: "" },
	{ name: "Hebra Mountains Northwest Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -2995, y: 3225, z: 539, details: "" },
	{ name: "Hebra South Summit Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 4, level: "Surface", x: -3398, y: 2499, z: 313, details: "" },
	{ name: "Hebra South Summit Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 4, level: "Surface", x: -3227, y: 2535, z: 441, details: "" },
	{ name: "Horon Lagoon Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 4243, y: -255, z: -16, details: "" },
	{ name: "Icefall Foothills Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -4429, y: 3760, z: 223, details: "" },
	{ name: "Isle of Rabac Gallery", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1554, y: 3102, z: 392, details: "" },
	{ name: "Kakariko Village Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 1947, y: -981, z: 157, details: "" },
	{ name: "Komo Shoreline Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 486, y: -3831, z: 7, details: "" },
	{ name: "Kopeeki Drifts Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -2395, y: 2276, z: 169, details: "" },
	{ name: "Koukot Plateau Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 14, level: "Surface", x: -2258, y: -1759, z: 56, details: "" },
	{ name: "Koukot Plateau Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 14, level: "Surface", x: -2173, y: -1841, z: 126, details: "" },
	{ name: "Lake Darman Monster Den", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2373, y: 3051, z: 445, details: "" },
	{ name: "Lake Ferona Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 7, level: "Surface", x: 1929, y: 1271, z: 121, details: "" },
	{ name: "Lake Ferona Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 7, level: "Surface", x: 1931, y: 1304, z: 168, details: "" },
	{ name: "Lake Hylia Whirlpool Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 125, y: -2501, z: -89, details: "" },
	{ name: "Lake Intenoch Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2485, y: 1792, z: 157, details: "" },
	{ name: "Lake Kilsie Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3930, y: 2861, z: -18, details: "" },
	{ name: "Lanayru Road East Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 11, level: "Surface", x: 3073, y: -1137, z: 91, details: "" },
	{ name: "Lanayru Road East Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 11, level: "Surface", x: 3476, y: -968, z: -8, details: "" },
	{ name: "Lanayru Road South Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 2698, y: -1314, z: 111, details: "" },
	{ name: "Lindor's Brow Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -1734, y: 1165, z: 228, details: "" },
	{ name: "Lizard's Burrow", landmark: "Cave", type: "", region: 7, level: "Surface", x: 2206, y: 3075, z: 405, details: "" },
	{ name: "Lower Spectacle Rock Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -1744, y: -2394, z: -11, details: "" },
	{ name: "Luto's Channel", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3094, y: -51, z: 79, details: "" },
	{ name: "Mapla Point Cave", landmark: "Cave", type: "", region: 11, level: "Surface", x: 4585, y: -2246, z: -1, details: "" },
	{ name: "Meadela's Mantle Cave", landmark: "Cave", type: "", region: 15, level: "Surface", x: -3982, y: -1245, z: 426, details: "" },
	{ name: "Mining Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Sky", x: 380, y: -1631, z: 1411, details: "" },
	{ name: "Mining Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Sky", x: 489, y: -1625, z: 1367, details: "" },
	{ name: "Mount Drena Foothill Cave", landmark: "Cave", type: "", region: 5, level: "Surface", x: -1372, y: 2861, z: 197, details: "" },
	{ name: "Mount Dunsel Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 12, level: "Surface", x: 3224, y: -3017, z: 59, details: "" },
	{ name: "Mount Dunsel Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 12, level: "Surface", x: 3291, y: -3296, z: 64, details: "" },
	{ name: "Mount Floria Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Surface", x: 1959, y: -2611, z: 71, details: "" },
	{ name: "Mount Floria Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Surface", x: 1789, y: -2985, z: 80, details: "" },
	{ name: "Mount Nabooru Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 14, level: "Surface", x: -1967, y: -2059, z: 30, details: "" },
	{ name: "Mount Nabooru Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 14, level: "Surface", x: -1795, y: -1961, z: 31, details: "" },
	{ name: "Mount Nabooru South Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -1726, y: -2183, z: 5, details: "" },
	{ name: "Mystathi's Shelf Cave", landmark: "Cave", type: "", region: 15, level: "Surface", x: -3881, y: -726, z: 569, details: "" },
	{ name: "North Akkala Beach Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 8, level: "Surface", x: 4650, y: 3584, z: -51, details: "" },
	{ name: "North Akkala Beach Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 8, level: "Surface", x: 4645, y: 3206, z: 6, details: "" },
	{ name: "North Biron Snowshelf Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3960, y: 3245, z: 236, details: "" },
	{ name: "North Hyrule Plain Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 3, level: "Surface", x: -1234, y: 770, z: 77, details: "" },
	{ name: "North Hyrule Plain Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 3, level: "Surface", x: -1188, y: 644, z: 72, details: "" },
	{ name: "Oakle's Navel Cave", landmark: "Cave", type: "", region: 11, level: "Surface", x: 2504, y: -2106, z: 6, details: "" },
	{ name: "Source of the Oasis Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -3354, y: -2693, z: -4, details: "" },
	{ name: "Oren Bridge Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 2909, y: -65, z: 81, details: "" },
	{ name: "Pagos Woods Excavation Site", landmark: "Cave", type: "", region: 13, level: "Surface", x: 671, y: -3109, z: 23, details: "" },
	{ name: "Passeri Greenbelt Cave", landmark: "Cave", type: "", region: 1, level: "Surface", x: -512, y: 127, z: 20, details: "" },
	{ name: "Pico Pond Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1247, y: 1231, z: 25, details: "" },
	{ name: "Pikida Stonegrove Northwest Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 5, level: "Surface", x: -2642, y: 3268, z: 249, details: "" },
	{ name: "Pikida Stonegrove Northwest Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 5, level: "Surface", x: -2414, y: 3136, z: 372, details: "" },
	{ name: "Pit Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 13, level: "Sky", x: 587, y: -1624, z: 1442, details: "" },
	{ name: "Pit Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 13, level: "Sky", x: 632, y: -1638, z: 1483, details: "" },
	{ name: "Ploymus Mountain Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3660, y: 538, z: 268, details: "" },
	{ name: "Pondside Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 2, level: "Sky", x: 260, y: -1557, z: 1361, details: "" },
	{ name: "Pondside Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 2, level: "Sky", x: 170, y: -1633, z: 1377, details: "" },
	{ name: "Popla Foothills Excavation Site", landmark: "Cave", type: "", region: 13, level: "Surface", x: 608, y: -2210, z: 50, details: "" },
	{ name: "Pristine Sanctum", landmark: "Cave", type: "(Entrance 1 of 2)", region: 9, level: "Surface", x: 3708, y: 608, z: 343, details: "" },
	{ name: "Pristine Sanctum", landmark: "Cave", type: "(Entrance 2 of 2)", region: 9, level: "Surface", x: 3622, y: 583, z: 169, details: "" },
	{ name: "Puffer Beach Overhead Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 283, y: -3851, z: 33, details: "" },
	{ name: "Quicksand Lake Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -3238, y: -2939, z: -65, details: "" },
	{ name: "Ralis Channel", landmark: "Cave", type: "(Entrance 1 of 2)", region: 9, level: "Surface", x: 2958, y: 253, z: 202, details: "" },
	{ name: "Ralis Channel", landmark: "Cave", type: "(Entrance 2 of 2)", region: 9, level: "Surface", x: 2912, y: 170, z: 157, details: "" },
	{ name: "Ranch Ruins Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 1, level: "Surface", x: 6, y: -157, z: 30, details: "" },
	{ name: "Ranch Ruins Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 1, level: "Surface", x: 37, y: -198, z: 18, details: "" },
	{ name: "Rassla Lake Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 1813, y: -3738, z: 118, details: "" },
	{ name: "Rauru Hillside Cave", landmark: "Cave", type: "", region: 6, level: "Surface", x: 676, y: 1389, z: 45, details: "" },
	{ name: "Rebonae Bridge Cave", landmark: "Cave", type: "", region: 1, level: "Surface", x: 845, y: 31, z: 15, details: "" },
	{ name: "Reservoir Lakefront Cavern", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3809, y: 419, z: 208, details: "" },
	{ name: "Retsam Forest Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 11, level: "Surface", x: 3748, y: -2026, z: 190, details: "" },
	{ name: "Retsam Forest Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 11, level: "Surface", x: 3757, y: -2066, z: 214, details: "" },
	{ name: "River of the Dead Waterfall Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -1092, y: -2162, z: 143, details: "" },
	{ name: "Robred Dropoff Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 2492, y: -1477, z: 12, details: "" },
	{ name: "Rodai Lakefront Tunnel", landmark: "Cave", type: "", region: 13, level: "Surface", x: 1896, y: -3111, z: 132, details: "" },
	{ name: "Rospro Pass Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3559, y: 2488, z: 227, details: "" },
	{ name: "Royal Hidden Passage", landmark: "Cave", type: "(Entrance 1 of 3)", region: 1, level: "Surface", x: -325, y: 802, z: 54, details: "" },
	{ name: "Royal Hidden Passage", landmark: "Cave", type: "(Entrance 2 of 3)", region: 1, level: "Surface", x: -253, y: 767, z: 27, details: "" },
	{ name: "Royal Hidden Passage", landmark: "Cave", type: "(Entrance 3 of 3)", region: 1, level: "Surface", x: -254, y: 129, z: 8, details: "" },
	{ name: "Sage Temple Cave", landmark: "Cave", type: "", region: 1, level: "Surface", x: -1404, y: -256, z: -3, details: "" },
	{ name: "Sahasra Slope Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 10, level: "Surface", x: 1328, y: -1156, z: 134, details: "" },
	{ name: "Sahasra Slope Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 10, level: "Surface", x: 1373, y: -1197, z: 129, details: "" },
	{ name: "Sarjon Woods Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 1203, y: -3170, z: 25, details: "" },
	{ name: "Satori Mountain Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -2151, y: -360, z: 276, details: "" },
	{ name: "Satori Mountain Foothill Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -2198, y: -807, z: 117, details: "" },
	{ name: "Shrine of Resurrection", landmark: "Cave", type: "", region: 2, level: "Surface", x: -1061, y: -1829, z: 142, details: "" },
	{ name: "Skull Lake Cave", landmark: "Cave", type: "", region: 8, level: "Surface", x: 3321, y: 3424, z: 171, details: "" },
	{ name: "South Gerudo Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -2939, y: -3857, z: -37, details: "" },
	{ name: "Southern Mine", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1800, y: 1983, z: 320, details: "" },
	{ name: "Spectacle Rock Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -2215, y: -2395, z: 247, details: "" },
	{ name: "Stalry Plateau Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -1527, y: -2222, z: -20, details: "" },
	{ name: "Statue of the Eighth Heroine Cave", landmark: "Cave", type: "", region: 15, level: "Surface", x: -4384, y: -536, z: 473, details: "" },
	{ name: "Sturnida Springs Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -4041, y: 2671, z: 23, details: "" },
	{ name: "Taafei Hill Cave", landmark: "Cave", type: "", region: 14, level: "Surface", x: -2457, y: -1798, z: 176, details: "" },
	{ name: "Tabahl Woods Cave", landmark: "Cave", type: "(Entrance 1 of 3)", region: 9, level: "Surface", x: 2674, y: 287, z: 89, details: "" },
	{ name: "Tabahl Woods Cave", landmark: "Cave", type: "(Entrance 2 of 3)", region: 9, level: "Surface", x: 2605, y: 227, z: 75, details: "" },
	{ name: "Tabahl Woods Cave", landmark: "Cave", type: "(Entrance 3 of 3)", region: 9, level: "Surface", x: 2679, y: 217, z: 92, details: "" },
	{ name: "Tabantha Hills Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -2840, y: 1771, z: 222, details: "" },
	{ name: "Talonto Peak Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3214, y: 2462, z: 345, details: "" },
	{ name: "Tamio River Downstream Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -2921, y: -804, z: 7, details: "" },
	{ name: "Tanagar Canyon East Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -2049, y: 1631, z: -56, details: "" },
	{ name: "Tanagar Canyon West Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -3308, y: 789, z: -101, details: "" },
	{ name: "Tarm Point Cave", landmark: "Cave", type: "", region: 11, level: "Surface", x: 4473, y: -826, z: 31, details: "" },
	{ name: "Tarrey Town Tunnel", landmark: "Cave", type: "", region: 8, level: "Surface", x: 3925, y: 1576, z: 107, details: "" },
	{ name: "Thundra Plateau Cave", landmark: "Cave", type: "", region: 3, level: "Surface", x: -2268, y: 899, z: 86, details: "" },
	{ name: "Tobio's Hollow Cave", landmark: "Cave", type: "", region: 10, level: "Surface", x: 1169, y: -2443, z: 177, details: "" },
	{ name: "Ubota Point Cave", landmark: "Cave", type: "", region: 13, level: "Surface", x: 1446, y: -3483, z: 77, details: "" },
	{ name: "Ulria Grotto East Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 9, level: "Surface", x: 4272, y: 774, z: 144, details: "" },
	{ name: "Ulria Grotto East Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 9, level: "Surface", x: 4505, y: 705, z: 96, details: "" },
	{ name: "Ulria Grotto South Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 4122, y: 662, z: 187, details: "" },
	{ name: "Upland Zorana Byroad Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 9, level: "Surface", x: 2863, y: 346, z: 227, details: "" },
	{ name: "Upland Zorana Byroad Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 9, level: "Surface", x: 2700, y: 479, z: 201, details: "" },
	{ name: "Upland Zorana Foothill Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 3147, y: 667, z: 177, details: "" },
	{ name: "Upland Zorana Mountainside Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 9, level: "Surface", x: 2570, y: 517, z: 164, details: "" },
	{ name: "Upland Zorana Mountainside Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 9, level: "Surface", x: 2633, y: 526, z: 188, details: "" },
	{ name: "Upland Zorana Summit Cave", landmark: "Cave", type: "", region: 9, level: "Surface", x: 2850, y: 477, z: 324, details: "" },
	{ name: "Valley of Silent Statues", landmark: "Cave", type: "", region: 14, level: "Surface", x: -3827, y: -2650, z: 35, details: "" },
	{ name: "Walnot Mountain Cave", landmark: "Cave", type: "(Entrance 1 of 2)", region: 11, level: "Surface", x: 4225, y: -1738, z: 180, details: "" },
	{ name: "Walnot Mountain Cave", landmark: "Cave", type: "(Entrance 2 of 2)", region: 11, level: "Surface", x: 3933, y: -2069, z: 127, details: "" },
	{ name: "West Gerudo Underground Ruins", landmark: "Cave", type: "", region: 14, level: "Surface", x: -4673, y: -1986, z: 9, details: "" },
	{ name: "West Lake Totori Cave", landmark: "Cave", type: "", region: 4, level: "Surface", x: -3958, y: 2029, z: 200, details: "" },
	{ name: "West Restaurant Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1642, y: 1729, z: 279, details: "" },
	{ name: "Whistling Hill Cave", landmark: "Cave", type: "", region: 2, level: "Surface", x: -72, y: -1045, z: 17, details: "" },
	{ name: "Yiga Blademaster Station", landmark: "Cave", type: "", region: 14, level: "Surface", x: -2433, y: -1819, z: 145, details: "" },
	{ name: "Yiga Clan Maritta Branch", landmark: "Cave", type: "", region: 6, level: "Surface", x: -643, y: 2040, z: 154, details: "" },
	{ name: "YunoboCo HQ East Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1764, y: 2837, z: 399, details: "" },
	{ name: "YunoboCo HQ South Cave", landmark: "Cave", type: "", region: 7, level: "Surface", x: 1713, y: 2718, z: 400, details: "" },
// CHASMS
	{ name: "Hyrule Castle Chasm", landmark: "Chasm", type: "", region: 1, level: "Surface", x: -254, y: 1012, z: -65, details: "" },
	{ name: "Hyrule Castle Moat East Chasm", landmark: "Chasm", type: "", region: 1, level: "Surface", x: 170, y: 882, z: 9, details: "" },
	{ name: "Hyrule Castle Moat West Chasm", landmark: "Chasm", type: "", region: 1, level: "Surface", x: -923, y: 667, z: 15, details: "" },
	{ name: "Hyrule Field Chasm", landmark: "Chasm", type: "", region: 1, level: "Surface", x: -251, y: -305, z: -479, details: "" },
	{ name: "Mount Daphnes Well", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -1313, y: -625, z: 9, details: "" },
	{ name: "Forest of Time Chasm", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -128, y: -1658, z: 10, details: "" },
	{ name: "Great Plateau East Chasm", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -450, y: -1993, z: 71, details: "" },
	{ name: "Great Plateau North Chasm", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -662, y: -1510, z: -518, details: "" },
	{ name: "Great Plateau South Chasm", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -930, y: -2316, z: 167, details: "" },
	{ name: "Great Plateau West Chasm", landmark: "Chasm", type: "", region: 2, level: "Surface", x: -1429, y: -1993, z: 231, details: "" },
	{ name: "Hyrule Ridge Chasm", landmark: "Chasm", type: "", region: 3, level: "Surface", x: -2645, y: 1126, z: 175, details: "" },
	{ name: "Rowan Plain Well", landmark: "Chasm", type: "", region: 3, level: "Surface", x: -1069, y: 2326, z: 99, details: "" },
	{ name: "Rito Village Chasm", landmark: "Chasm", type: "", region: 4, level: "Surface", x: -3571, y: 1803, z: 123, details: "" },
	{ name: "North Lomei Chasm", landmark: "Chasm", type: "", region: 5, level: "Surface", x: -814, y: 3535, z: 235, details: "" },
	{ name: "Deku Tree Chasm", landmark: "Chasm", type: "", region: 6, level: "Surface", x: 418, y: 2193, z: 144, details: "" },
	{ name: "Drenan Highlands Chasm", landmark: "Chasm", type: "", region: 6, level: "Surface", x: -63, y: 2984, z: 127, details: "" },
	{ name: "Elma Knolls Chasm", landmark: "Chasm", type: "", region: 6, level: "Surface", x: -453, y: 1721, z: 169, details: "" },
	{ name: "Death Mountain Chasm", landmark: "Chasm", type: "", region: 7, level: "Surface", x: 2535, y: 2603, z: 644, details: "" },
	{ name: "Minshi Woods Chasm", landmark: "Chasm", type: "", region: 7, level: "Surface", x: 1055, y: 1668, z: 150, details: "" },
	{ name: "East Akkala Plains Chasm", landmark: "Chasm", type: "", region: 8, level: "Surface", x: 4037, y: 2177, z: 29, details: "" },
	{ name: "Lomei Labyrinth Chasm", landmark: "Chasm", type: "", region: 8, level: "Surface", x: 4663, y: 3697, z: 50, details: "" },
	{ name: "Skull Lake Chasm", landmark: "Chasm", type: "", region: 8, level: "Surface", x: 3248, y: 3441, z: -43, details: "" },
	{ name: "South Akkala Plains Chasm", landmark: "Chasm", type: "", region: 8, level: "Surface", x: 3284, y: 1303, z: 217, details: "" },
	{ name: "Chasm Under Zora's Domain", landmark: "Chasm", type: "", region: 9, level: "Surface", x: 3272, y: 442, z: -21, details: "" },
	{ name: "Tingel Island Chasm", landmark: "Chasm", type: "", region: 9, level: "Surface", x: 4708, y: 1308, z: 61, details: "" },
	{ name: "East Hill Chasm", landmark: "Chasm", type: "", region: 10, level: "Surface", x: 1974, y: -855, z: 178, details: "" },
	{ name: "Lanayru Wetlands Chasm", landmark: "Chasm", type: "", region: 10, level: "Surface", x: 1727, y: 158, z: -5, details: "" },
	{ name: "Naydra Snowfield Chasm", landmark: "Chasm", type: "", region: 11, level: "Surface", x: 3591, y: -1341, z: 117, details: "" },
	{ name: "Eventide Island Chasm", landmark: "Chasm", type: "", region: 12, level: "Surface", x: 4507, y: -3459, z: -17, details: "" },
	{ name: "Meda Mountain Chasm", landmark: "Chasm", type: "", region: 12, level: "Surface", x: 2513, y: -2380, z: 131, details: "" },
	{ name: "Hills of Baumer Chasm", landmark: "Chasm", type: "", region: 13, level: "Surface", x: 222, y: -2119, z: 53, details: "" },
	{ name: "Lake Hylia Chasm", landmark: "Chasm", type: "", region: 13, level: "Surface", x: -332, y: -2598, z: -52, details: "" },
	{ name: "South Nabi Lake Well", landmark: "Chasm", type: "", region: 13, level: "Surface", x: 783, y: -1497, z: 21, details: "" },
	{ name: "Tobio's Hollow Chasm", landmark: "Chasm", type: "", region: 13, level: "Surface", x: 1305, y: -2397, z: 62, details: "" },
	{ name: "East Gerudo Chasm", landmark: "Chasm", type: "", region: 14, level: "Surface", x: -2491, y: -3068, z: 81, details: "" },
	{ name: "South Lomei Chasm", landmark: "Chasm", type: "", region: 14, level: "Surface", x: -1795, y: -3462, z: 46, details: "" },
	{ name: "Birida Lookout Chasm", landmark: "Chasm", type: "", region: 15, level: "Surface", x: -3680, y: -1853, z: 76, details: "" },
	{ name: "Gerudo Summit Chasm", landmark: "Chasm", type: "", region: 15, level: "Surface", x: -4203, y: -639, z: 682, details: "" },
	{ name: "Yiga Clan Hideout Chasm", landmark: "Chasm", type: "", region: 15, level: "Surface", x: -3429, y: -1334, z: 335, details: "" },
// DISPENSERS
{ name: "Gerudo Canyon Pass Dispenser", landmark: "Dispenser", type: "", region: 2, level: "Surface", x: -1619, y: -1888, z: 1, details: "Battery, Big Wheel, Portable Pot, Spring, Stake" },
{ name: "South Hyrule Sky Dispenser", landmark: "Dispenser", type: "", region: 2, level: "Sky", x: -1212, y: -1585, z: 1006, details: "Light, Rocket, Small Wheel, Time Bomb" },
{ name: "Courage Island Dispenser", landmark: "Dispenser", type: "", region: 3, level: "Sky", x: -2370, y: 781, z: 610, details: "Balloon, Fan, Portable Pot, Time Bomb" },
{ name: "Lightcast Island Dispenser", landmark: "Dispenser", type: "", region: 3, level: "Sky", x: -3612, y: 1066, z: 1655, details: "Balloon, Hover Stone, Mirror, Spring, Wing" },
{ name: "Tabantha Sky Dispenser", landmark: "Dispenser", type: "", region: 3, level: "Sky", x: -3455, y: 393, z: 1694, details: "Frost Emitter, Mirror, Small Wheel, Wing" },
{ name: "West Hebra Sky Dispenser", landmark: "Dispenser", type: "", region: 4, level: "Sky", x: -3803, y: 2766, z: 701, details: "Flame Emitter, Portable Pot, Rocket, Time Bomb" },
{ name: "East Hebra Sky Dispenser", landmark: "Dispenser", type: "", region: 5, level: "Sky", x: -1705, y: 3371, z: 947, details: "Cart, Fan, Light, Sled, Wing" },
{ name: "Bravery Island Dispenser", landmark: "Dispenser", type: "", region: 6, level: "Sky", x: 215, y: 1981, z: 754, details: "Battery, Construct Head, Flame Emitter, Light" },
{ name: "North Hyrule Sky Dispenser", landmark: "Dispenser", type: "", region: 6, level: "Sky", x: 443, y: 2821, z: 1819, details: "Homing Cart, Light, Shock Emitter, Steering Stick" },
{ name: "Death Mountain Depths Dispenser", landmark: "Dispenser", type: "", region: 7, level: "Depths", x: 2190, y: 2640, z: -963, details: "Battery, Big Wheel, Portable Pot, Steering Stick" },
{ name: "South Eldin Sky Dispenser", landmark: "Dispenser", type: "", region: 7, level: "Sky", x: 1983, y: 1221, z: 1250, details: "Battery, Big Wheel, Fan, Hydrant" },
{ name: "Sky Mine Dispenser", landmark: "Dispenser", type: "", region: 8, level: "Sky", x: 4557, y: 2076, z: 1154, details: "Homing Cart, Hover Stone, Hydrant, Time Bomb" },
{ name: "Sokkala Sky Dispenser", landmark: "Dispenser", type: "", region: 8, level: "Sky", x: 3755, y: 1542, z: 1156, details: "Cannon, Cart, Construct Head, Homing Cart, Stake" },
{ name: "Hudson Construction Site Dispenser", landmark: "Dispenser", type: "", region: 8, level: "Surface", x: 3807, y: 1561, z: 89, details: "Balloon, Big Wheel, Small Wheel, Fan, Rocket, Steering Stick" },
{ name: "Lanayru Sky Dispenser", landmark: "Dispenser", type: "", region: 9, level: "Sky", x: 2915, y: 502, z: 950, details: "Beam Emitter, Cart, Fan, Wing" },
{ name: "Wellspring Island Dispenser", landmark: "Dispenser", type: "", region: 9, level: "Sky", x: 3430, y: 636, z: 1316, details: "Battery, Fan, Hover Stone, Stabilizer, Wing" },
{ name: "Kakariko Village Dispenser", landmark: "Dispenser", type: "", region: 10, level: "Surface", x: 1838, y: -1093, z: 154, details: "Balloon, Big Wheel, Fan, Stabilizer" },
{ name: "North Necluda Sky Dispenser", landmark: "Dispenser", type: "", region: 10, level: "Sky", x: 1778, y: -1096, z: 917, details: "Cannon, Spring, Time Bomb, Wing" },
{ name: "West Necluda Sky Dispenser", landmark: "Dispenser", type: "", region: 10, level: "Sky", x: 1344, y: -2151, z: 584, details: "Balloon, Cart, Construct Head, Hydrant, Stabilizer" },
{ name: "Zonaite Forge Island Dispenser", landmark: "Dispenser", type: "", region: 10, level: "Sky", x: 2320, y: -1718, z: 1484, details: "Beam Emitter, Flame Emitter, Frost Emitter, Homing Cart, Time Bomb" },
{ name: "South Lanayru Sky Dispenser", landmark: "Dispenser", type: "", region: 11, level: "Sky", x: 4675, y: -1029, z: 1788, details: "Battery, Frost Emitter, Mirror, Wing" },
{ name: "Valor Island Dispenser", landmark: "Dispenser", type: "", region: 11, level: "Sky", x: 4510, y: -805, z: 1116, details: "Beam Emitter, Hydrant, Spring, Steering Stick" },
{ name: "South Necluda Sky Dispenser", landmark: "Dispenser", type: "", region: 12, level: "Sky", x: 2851, y: -2958, z: 1211, details: "Cannon, Light, Small Wheel, Steering Stick" },
{ name: "Left-Leg Depot Dispenser", landmark: "Dispenser", type: "", region: 13, level: "Depths", x: 1058, y: -2320, z: -553, details: "Big Wheel, Construct Head, Rocket, Small Wheel, Steering Stick, Wing" },
{ name: "Dragonhead Island Dispenser", landmark: "Dispenser", type: "", region: 13, level: "Sky", x: 1390, y: -3239, z: 416, details: "Cart, Fan, Steering Stick, Wing" },
{ name: "Great Sky Island East Dispenser", landmark: "Dispenser", type: "", region: 13, level: "Sky", x: 769, y: -1259, z: 1578, details: "Fan, Flame Emitter, Portable Pot, Wing" },
{ name: "Great Sky Island South Dispenser", landmark: "Dispenser", type: "", region: 13, level: "Sky", x: 435, y: -1686, z: 1442, details: "Fan, Flame Emitter, Portable Pot" },
{ name: "Thunderhead Isles Dispenser", landmark: "Dispenser", type: "", region: 13, level: "Sky", x: 1104, y: -3331, z: 827, details: "Battery, Fan, Portable Pot, Shock Emitter" },
{ name: "East Gerudo Sky Dispenser", landmark: "Dispenser", type: "", region: 14, level: "Sky", x: -1771, y: -2019, z: 1147, details: "Beam Emitter, Mirror, Sled, Stake, Steering Stick" },
{ name: "Starview Island Dispenser", landmark: "Dispenser", type: "", region: 15, level: "Sky", x: -3457, y: -373, z: 1942, details: "Frost Emitter, Shock Emitter, Sled, Stabilizer, Stake" }
];